# Generated by Django 4.2.1 on 2023-05-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Usuario",),
    ]
