# Generated by Django 4.2.1 on 2023-05-11 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_comentarios"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotasAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        choices=[
                            ("p", "Péssimo"),
                            ("r", "Ruim"),
                            ("re", "Regular"),
                            ("b", "Bom"),
                            ("o", "Ótimo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="home.aulas"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
